[tool.poetry]
name = "app"
version = "0.2.0"
description = ""
authors = ["KiraLT <certbot-lambda@kiralt.dev>"]
packages = [
    { include = "app" },
]

[tool.poetry.dependencies]
python = "~3.9"
certbot = "^1.22.0"
boto3 = "^1.20.37"
certbot-dns-route53 = "^1.22.0"
certbot-dns-cloudflare = "^1.22.0"
certbot-dns-cloudxns = "^1.22.0"
certbot-dns-digitalocean = "^1.22.0"
certbot-dns-dnsimple = "^1.22.0"
certbot-dns-dnsmadeeasy = "^1.22.0"
certbot-dns-gehirn = "^1.22.0"
certbot-dns-google = "^1.22.0"
certbot-dns-linode = "^1.22.0"
certbot-dns-luadns = "^1.22.0"
certbot-dns-nsone = "^1.22.0"
certbot-dns-ovh = "^1.22.0"
certbot-dns-rfc2136 = "^1.22.0"
certbot-dns-sakuracloud = "^1.22.0"
python-dotenv = "^0.19.2"
python-slugify = "^5.0.2"

[tool.poetry.dev-dependencies]
taskipy = "^1.9.0"
pex = "^2.1.62"
lambdex = "^0.1.6"
black = "^21.12b0"
python-semantic-release = "^7.31.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.taskipy.tasks]
build = "rm -rf ./dist && task build-pex && task build-lambda"
build-pex = "pex . -o dist/certbot-lambda.zip"
build-lambda = "lambdex build -e app.handler:handler dist/certbot-lambda.zip"
test = "lambdex test --empty dist/certbot-lambda.zip"
dev = "python -c 'from app.handler import handler; handler(None, None)'"
prettify = "black ./app"
release = "semantic-release publish"

[tool.semantic_release]
version_variable = [
    "app/__init__.py:__version__",
    "pyproject.toml:version"
]
branch = "main"
hvcs = "github"
upload_to_pypi = false
upload_to_release = true
build_command = "poetry run task build"
commit_subject = "Release {version} [skip ci]"
