[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["KiraLT <certbot-lambda@kiralt.dev>"]
packages = [
    { include = "app" },
]

[tool.poetry.dependencies]
python = "~3.9"
certbot = "^1.22.0"
boto3 = "^1.20.37"
certbot-dns-route53 = "^1.22.0"
pydantic = "^1.9.0"

[tool.poetry.dev-dependencies]
taskipy = "^1.9.0"
pex = "^2.1.62"
lambdex = "^0.1.6"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.taskipy.tasks]
build = "rm -rf ./build && task build-pex && task build-lambda"
build-pex = "pex . -o build/certbot-lambda.zip"
build-lambda = "lambdex build -e app.handler:handler build/certbot-lambda.zip"
test = "lambdex test --empty build/certbot-lambda.zip"
dev = "python -c 'from app.handler import handler; handler(None, None)'"
