# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Create release
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install poetry
      run: pipx install poetry

    - uses: actions/setup-python@v4
      with:
        python-version: 3.9
        cache: poetry

    - name: Configure poetry
      run: poetry config virtualenvs.in-project true

    - name: Install dependencies
      run: poetry install

    - name: Semantic Release
      env:
        GH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
      run: |
        git config user.name github-actions
        git config user.email actions@github.com
        poetry run task release
