# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Release
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Python Poetry
      uses: abatilo/actions-poetry@v2.1.4
      with:
        poetry-version: 1.1.2
    - name: Configure poetry
      run: poetry config virtualenvs.in-project true
    - name: Install dependencies
      run: |
        poetry install
    - name: Semantic Release
      env:
        GL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
      run: |
        poetry run task release
